# Generated by Django 5.1.3 on 2026-02-13 07:31

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingImageOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('organization_name', models.CharField(help_text="Name of organization (e.g., 'First Baptist Church')", max_length=255)),
                ('coordinator_name', models.CharField(max_length=255)),
                ('coordinator_email', models.EmailField(max_length=254)),
                ('coordinator_phone', models.CharField(max_length=20)),
                ('title', models.CharField(help_text="e.g., 'Church Anniversary Shirts 2025'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the clothing order')),
                ('price_per_item', models.DecimalField(decimal_places=2, help_text='Price per item in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requires_custom_name', models.BooleanField(default=False, help_text='If True, participants can provide custom names for printing')),
                ('requires_image', models.BooleanField(default=False, help_text="If True, image upload is mandatory; if False, it's optional")),
                ('order_deadline', models.DateTimeField(blank=True, help_text='Deadline for participants to join and pay', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If False, order is closed and new participants cannot join')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_image_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clothing Image Order',
                'verbose_name_plural': 'Clothing Image Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingCouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='clothing_image_orders.clothingimageorder')),
            ],
            options={
                'verbose_name': 'Clothing Coupon Code',
                'verbose_name_plural': 'Clothing Coupon Codes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingOrderParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('serial_number', models.PositiveIntegerField(editable=False, help_text='Auto-incrementing number within the order')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=10)),
                ('custom_name', models.CharField(blank=True, help_text='Custom name to print on clothing (if enabled)', max_length=255, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional image upload (PNG, JPG, JPEG - max 5MB)', max_length=255, null=True, verbose_name='image')),
                ('paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='clothing_image_orders.clothingcouponcode')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clothing_image_orders.clothingimageorder')),
            ],
            options={
                'verbose_name': 'Clothing Order Participant',
                'verbose_name_plural': 'Clothing Order Participants',
                'ordering': ['order', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='clothingimageorder',
            index=models.Index(fields=['reference'], name='clo_img_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingimageorder',
            index=models.Index(fields=['organization_name'], name='clo_img_org_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingimageorder',
            index=models.Index(fields=['is_active'], name='clo_img_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingimageorder',
            index=models.Index(fields=['created_at'], name='clo_img_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingcouponcode',
            index=models.Index(fields=['order', 'is_used'], name='clo_coupon_order_used_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingcouponcode',
            index=models.Index(fields=['code'], name='clo_coupon_code_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingorderparticipant',
            index=models.Index(fields=['reference'], name='clo_part_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingorderparticipant',
            index=models.Index(fields=['order', 'serial_number'], name='clo_part_order_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingorderparticipant',
            index=models.Index(fields=['email'], name='clo_part_email_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingorderparticipant',
            index=models.Index(fields=['size'], name='clo_part_size_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingorderparticipant',
            index=models.Index(fields=['paid'], name='clo_part_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingorderparticipant',
            index=models.Index(fields=['created_at'], name='clo_part_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clothingorderparticipant',
            unique_together={('order', 'serial_number')},
        ),
    ]
