# Generated by Django 5.1.3 on 2026-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveformlink',
            name='last_serial_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
