# Generated by Django 5.1.3 on 2026-02-09 23:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalmedia',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Promotional media file (image or video)', max_length=255, null=True, verbose_name='media'),
        ),
    ]
