# Generated by Django 5.1.3 on 2026-02-08 08:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBulkOrderLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('custom_branding_enabled', models.BooleanField(default=False)),
                ('payment_deadline', models.DateTimeField()),
                ('image_required', models.BooleanField(default=True)),
                ('max_image_size_mb', models.PositiveIntegerField(default=5)),
                ('allowed_image_formats', models.JSONField(default=list, help_text='Allowed formats: jpg, jpeg, png, webp')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending Generation'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_zip_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_bulk_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Bulk Order Link',
                'verbose_name_plural': 'Image Bulk Order Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageCouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='image_bulk_orders.imagebulkorderlink')),
            ],
            options={
                'verbose_name': 'Image Coupon Code',
                'verbose_name_plural': 'Image Coupon Codes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageOrderEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('serial_number', models.PositiveIntegerField(editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=10)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_image', models.URLField(help_text='Cloudinary URL of uploaded image')),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID for image management', max_length=255)),
                ('image_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='image_bulk_orders.imagebulkorderlink')),
                ('coupon_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_bulk_orders.imagecouponcode')),
            ],
            options={
                'verbose_name': 'Image Order Entry',
                'verbose_name_plural': 'Image Order Entries',
                'ordering': ['bulk_order', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['slug'], name='img_bulk_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['created_by', 'payment_deadline'], name='img_bulk_user_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['organization_name'], name='img_bulk_org_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['created_at'], name='img_bulk_created_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['generation_status'], name='img_bulk_gen_status_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecouponcode',
            index=models.Index(fields=['bulk_order', 'is_used'], name='img_coupon_bulk_used_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecouponcode',
            index=models.Index(fields=['code'], name='img_coupon_code_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['bulk_order', 'paid'], name='img_order_bulk_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['reference'], name='img_order_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['size', 'paid'], name='img_order_size_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['email'], name='img_order_email_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['created_at'], name='img_order_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imageorderentry',
            unique_together={('bulk_order', 'serial_number')},
        ),
    ]
