# Generated by Django 5.1.3 on 2026-02-10 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the faculty (e.g., Faculty of Engineering)', max_length=255)),
                ('abbreviation', models.CharField(help_text='Short form (e.g., ENG, SCI, ARTS)', max_length=20, validators=[django.core.validators.RegexValidator(message='Abbreviation must contain only uppercase letters', regex='^[A-Z]+$')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the faculty is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['university__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the department (e.g., Computer Science)', max_length=255)),
                ('abbreviation', models.CharField(help_text='Short form (e.g., CSC, MEE, CHE)', max_length=20, validators=[django.core.validators.RegexValidator(message='Abbreviation must contain only uppercase letters', regex='^[A-Z]+$')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the department is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academic_directory.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['faculty__university__name', 'faculty__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_years', models.PositiveIntegerField(help_text='Number of years for the program (4-7 years)', validators=[django.core.validators.MinValueValidator(4, message='Program duration must be at least 4 years'), django.core.validators.MaxValueValidator(7, message='Program duration cannot exceed 7 years')])),
                ('program_type', models.CharField(choices=[('BSC', 'Bachelor of Science (B.Sc)'), ('BENG', 'Bachelor of Engineering (B.Eng)'), ('BTECH', 'Bachelor of Technology (B.Tech)'), ('BA', 'Bachelor of Arts (B.A)'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)'), ('LLB', 'Bachelor of Laws (LLB)'), ('BARCH', 'Bachelor of Architecture (B.Arch)'), ('BAGRICULTURE', 'Bachelor of Agriculture (B.Agriculture)'), ('BPHARM', 'Bachelor of Pharmacy (B.Pharm)'), ('OTHER', 'Other')], default='BSC', help_text='Type of degree program', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the program (e.g., special requirements)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(help_text='Department this program duration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='programduration', to='academic_directory.department')),
            ],
            options={
                'verbose_name': 'Program Duration',
                'verbose_name_plural': 'Program Durations',
                'ordering': ['department__faculty__university__name', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full legal name of the representative', max_length=255)),
                ('nickname', models.CharField(blank=True, help_text='Optional preferred name or nickname', max_length=100, null=True)),
                ('phone_number', models.CharField(help_text='Primary contact number (unique identifier)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+2348012345678' or '08012345678'", regex='^\\+?234?\\d{10,11}$')])),
                ('whatsapp_number', models.CharField(blank=True, help_text='Optional WhatsApp contact number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+2348012345678' or '08012345678'", regex='^\\+?234?\\d{10,11}$')])),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True)),
                ('role', models.CharField(choices=[('CLASS_REP', 'Class Representative'), ('DEPT_PRESIDENT', 'Department President'), ('FACULTY_PRESIDENT', 'Faculty President')], help_text='Type of representative role', max_length=20)),
                ('entry_year', models.PositiveIntegerField(blank=True, help_text='Year student entered the program (for class reps only)', null=True)),
                ('tenure_start_year', models.PositiveIntegerField(blank=True, help_text='Year representative took office (for presidents)', null=True)),
                ('submission_source', models.CharField(choices=[('WEBSITE', 'Website Submission'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PHONE', 'Phone Call'), ('SMS', 'SMS'), ('MANUAL', 'Manual Entry'), ('IMPORT', 'Bulk Import'), ('OTHER', 'Other')], default='WEBSITE', help_text='How this data was submitted', max_length=20)),
                ('submission_source_other', models.CharField(blank=True, help_text="Free text description if source is 'Other'", max_length=100, null=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed')], default='UNVERIFIED', help_text='Verification status of this entry', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when verification occurred', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes about this representative', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this representative is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department the representative belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='academic_directory.department')),
                ('faculty', models.ForeignKey(help_text='Faculty (denormalized for faster queries)', on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='academic_directory.faculty')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin user who verified this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_representatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Representative',
                'verbose_name_plural': 'Representatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this notification has been read by an admin')),
                ('is_emailed', models.BooleanField(default=False, help_text='Whether email notification was sent')),
                ('emailed_at', models.DateTimeField(blank=True, help_text='When email notification was sent', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was marked as read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created')),
                ('read_by', models.ForeignKey(blank=True, help_text='Admin user who read this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('representative', models.OneToOneField(help_text='Representative this notification is for', on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='academic_directory.representative')),
            ],
            options={
                'verbose_name': 'Submission Notification',
                'verbose_name_plural': 'Submission Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full official name of the university', max_length=255, unique=True)),
                ('abbreviation', models.CharField(help_text='Short form (e.g., UNIBEN, UI, UNILAG)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Abbreviation must contain only uppercase letters', regex='^[A-Z]+$')])),
                ('state', models.CharField(choices=[('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKWA_IBOM', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS_RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('FCT', 'Federal Capital Territory'), ('GOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOBE', 'Yobe'), ('ZAMFARA', 'Zamfara')], help_text='Nigerian state where the university is located', max_length=50)),
                ('type', models.CharField(choices=[('FEDERAL', 'Federal University'), ('STATE', 'State University'), ('PRIVATE', 'Private University')], default='FEDERAL', help_text='Federal, State, or Private university', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the university is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['abbreviation'], name='academic_di_abbrevi_29b27c_idx'), models.Index(fields=['state'], name='academic_di_state_89b6d4_idx'), models.Index(fields=['type'], name='academic_di_type_a359e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(help_text='Role at time of snapshot', max_length=20)),
                ('entry_year', models.PositiveIntegerField(blank=True, help_text='Entry year at time of snapshot', null=True)),
                ('tenure_start_year', models.PositiveIntegerField(blank=True, help_text='Tenure start at time of snapshot', null=True)),
                ('verification_status', models.CharField(help_text='Verification status at time of snapshot', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Active status at time of snapshot')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was created')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this historical record', null=True)),
                ('department', models.ForeignKey(help_text='Department at time of snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_directory.department')),
                ('faculty', models.ForeignKey(help_text='Faculty at time of snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_directory.faculty')),
                ('representative', models.ForeignKey(help_text='Representative this history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='academic_directory.representative')),
                ('university', models.ForeignKey(help_text='University at time of snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_directory.university')),
            ],
            options={
                'verbose_name': 'Representative History',
                'verbose_name_plural': 'Representative Histories',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AddField(
            model_name='representative',
            name='university',
            field=models.ForeignKey(help_text='University (denormalized for faster queries)', on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='academic_directory.university'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(help_text='University this faculty belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='academic_directory.university'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['faculty', 'name'], name='academic_di_faculty_4e9018_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['abbreviation'], name='academic_di_abbrevi_268d7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'name')},
        ),
        migrations.AddIndex(
            model_name='submissionnotification',
            index=models.Index(fields=['is_read', '-created_at'], name='academic_di_is_read_fe9391_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionnotification',
            index=models.Index(fields=['is_emailed'], name='academic_di_is_emai_403357_idx'),
        ),
        migrations.AddIndex(
            model_name='representativehistory',
            index=models.Index(fields=['representative', '-snapshot_date'], name='academic_di_represe_9b64ec_idx'),
        ),
        migrations.AddIndex(
            model_name='representativehistory',
            index=models.Index(fields=['phone_number'], name='academic_di_phone_n_b88114_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['phone_number'], name='academic_di_phone_n_d8b6af_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['department', 'role'], name='academic_di_departm_e49278_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['faculty', 'role'], name='academic_di_faculty_be8b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['university', 'role'], name='academic_di_univers_ad1619_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['verification_status'], name='academic_di_verific_356da0_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['is_active'], name='academic_di_is_acti_2efacf_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['entry_year'], name='academic_di_entry_y_f5ccdc_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['tenure_start_year'], name='academic_di_tenure__ce8b76_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['university', 'name'], name='academic_di_univers_9de54e_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['abbreviation'], name='academic_di_abbrevi_e45458_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'name')},
        ),
    ]
