# Generated by Django 5.1.3 on 2026-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nysckitorder',
            name='call_up_number',
            field=models.CharField(help_text='NYSC call-up number (e.g., AB/22C/1234)', max_length=20),
        ),
    ]
