# Generated by Django 5.1.3 on 2026-01-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nysckit',
            options={'ordering': [models.Case(models.When(then=0, type='kakhi'), models.When(then=2, type='vest'), models.When(then=1, type='cap'), default=3), 'type'], 'verbose_name': 'nysckit', 'verbose_name_plural': 'nysckits'},
        ),
        migrations.AddIndex(
            model_name='nysckit',
            index=models.Index(fields=['name'], name='products_ny_name_d97dca_idx'),
        ),
        migrations.AddIndex(
            model_name='nysckit',
            index=models.Index(fields=['slug'], name='products_ny_slug_5d85ca_idx'),
        ),
        migrations.AddIndex(
            model_name='nysckit',
            index=models.Index(fields=['type'], name='products_ny_type_c88e72_idx'),
        ),
    ]
